- Reference: https://www.bilibili.com/video/BV1hE411t7RN?p=14

# Dataset

In [1]:
from torch.utils.data import Dataset

In [ ]:
Dataset??
# __len__(self)
# __getitem__(self, item)

In [2]:
from PIL import Image

In [3]:
class MyData(Dataset):

    def __init__(self, root_dir, label_dir):
        self.root_dir = root_dir 
        self.label_dir = label_dir
        self.path = os.path.join(self.root_dir, self.label_dir)
        self.img_path = os.listdir(self.path)
        
    def __getitem__(self, idx):
        img_name = self.img_path[idx]
        img_item_path = os.path.join(self.root_dir, self.label_dir, img_name)
        img = Image.open(img_item_path)
        label = self.label_dir
        return img, label 
        
    def __len__(self):
        return len(self.img_path)

In [ ]:
ants_dataset = MyData()

# TensorBoard

In [5]:
from torch.utils.tensorboard import SummaryWriter

## add_scalar

In [8]:
writer = SummaryWriter("logs")

#writer.add_image()
for i in range(100):
    writer.add_scalar(tag='y=x', scalar_value=i, global_step=i)
writer.close()

In [10]:
!tensorboard --logdir=logs --port=6006

^C


## add_image

In [16]:
from PIL import Image
img_path = './data/train/ants_image/0013035.jpg'
img = Image.open(img_path)

import numpy as np 
img_arr = np.array(img)

In [17]:
writer.add_image('test', img_arr, 2, dataformats='HWC')
writer.close()

In [18]:
!tensorboard --logdir=logs --port=6006

^C


# transforms

In [19]:
from torchvision import transforms
from PIL import Image
img_path = './data/train/ants_image/0013035.jpg'
img = Image.open(img_path)

## ToTensor

In [20]:
tensor_trans = transforms.ToTensor()
tensor_img = tensor_trans(img)

tensor_img

tensor([[[0.3137, 0.3137, 0.3137,  ..., 0.3176, 0.3098, 0.2980],
         [0.3176, 0.3176, 0.3176,  ..., 0.3176, 0.3098, 0.2980],
         [0.3216, 0.3216, 0.3216,  ..., 0.3137, 0.3098, 0.3020],
         ...,
         [0.3412, 0.3412, 0.3373,  ..., 0.1725, 0.3725, 0.3529],
         [0.3412, 0.3412, 0.3373,  ..., 0.3294, 0.3529, 0.3294],
         [0.3412, 0.3412, 0.3373,  ..., 0.3098, 0.3059, 0.3294]],

        [[0.5922, 0.5922, 0.5922,  ..., 0.5961, 0.5882, 0.5765],
         [0.5961, 0.5961, 0.5961,  ..., 0.5961, 0.5882, 0.5765],
         [0.6000, 0.6000, 0.6000,  ..., 0.5922, 0.5882, 0.5804],
         ...,
         [0.6275, 0.6275, 0.6235,  ..., 0.3608, 0.6196, 0.6157],
         [0.6275, 0.6275, 0.6235,  ..., 0.5765, 0.6275, 0.5961],
         [0.6275, 0.6275, 0.6235,  ..., 0.6275, 0.6235, 0.6314]],

        [[0.9137, 0.9137, 0.9137,  ..., 0.9176, 0.9098, 0.8980],
         [0.9176, 0.9176, 0.9176,  ..., 0.9176, 0.9098, 0.8980],
         [0.9216, 0.9216, 0.9216,  ..., 0.9137, 0.9098, 0.

In [21]:
import cv2
cv_img = cv2.imread(img_path)
cv_img

array([[[233, 151,  80],
        [233, 151,  80],
        [233, 151,  80],
        ...,
        [234, 152,  81],
        [232, 150,  79],
        [229, 147,  76]],

       [[234, 152,  81],
        [234, 152,  81],
        [234, 152,  81],
        ...,
        [234, 152,  81],
        [232, 150,  79],
        [229, 147,  76]],

       [[235, 153,  82],
        [235, 153,  82],
        [235, 153,  82],
        ...,
        [233, 151,  80],
        [232, 150,  79],
        [230, 148,  77]],

       ...,

       [[237, 160,  87],
        [237, 160,  87],
        [236, 159,  86],
        ...,
        [141,  92,  44],
        [235, 158,  95],
        [228, 157,  90]],

       [[237, 160,  87],
        [237, 160,  87],
        [236, 159,  86],
        ...,
        [226, 147,  84],
        [255, 160,  90],
        [233, 152,  84]],

       [[237, 160,  87],
        [237, 160,  87],
        [236, 159,  86],
        ...,
        [242, 160,  79],
        [250, 159,  78],
        [233, 161,  84]]

In [22]:
from torch.utils.tensorboard import SummaryWriter

In [23]:
writer = SummaryWriter('logs')
writer.add_image('tensor_img', tensor_img)
writer.close()

In [24]:
!tensorboard --logdir=logs --port=6006

^C


## Normalize

In [27]:
trans_norm = transforms.Normalize(mean=[0.5, 0.5, 0.5], std=[0.5, 0.5, 0.5])
img_norm = trans_norm(tensor_img)
img_norm

tensor([[[-0.3725, -0.3725, -0.3725,  ..., -0.3647, -0.3804, -0.4039],
         [-0.3647, -0.3647, -0.3647,  ..., -0.3647, -0.3804, -0.4039],
         [-0.3569, -0.3569, -0.3569,  ..., -0.3725, -0.3804, -0.3961],
         ...,
         [-0.3176, -0.3176, -0.3255,  ..., -0.6549, -0.2549, -0.2941],
         [-0.3176, -0.3176, -0.3255,  ..., -0.3412, -0.2941, -0.3412],
         [-0.3176, -0.3176, -0.3255,  ..., -0.3804, -0.3882, -0.3412]],

        [[ 0.1843,  0.1843,  0.1843,  ...,  0.1922,  0.1765,  0.1529],
         [ 0.1922,  0.1922,  0.1922,  ...,  0.1922,  0.1765,  0.1529],
         [ 0.2000,  0.2000,  0.2000,  ...,  0.1843,  0.1765,  0.1608],
         ...,
         [ 0.2549,  0.2549,  0.2471,  ..., -0.2784,  0.2392,  0.2314],
         [ 0.2549,  0.2549,  0.2471,  ...,  0.1529,  0.2549,  0.1922],
         [ 0.2549,  0.2549,  0.2471,  ...,  0.2549,  0.2471,  0.2627]],

        [[ 0.8275,  0.8275,  0.8275,  ...,  0.8353,  0.8196,  0.7961],
         [ 0.8353,  0.8353,  0.8353,  ...,  0

In [28]:
writer = SummaryWriter('logs')
writer.add_image('norm_img', img_norm)
writer.close()

In [29]:
!tensorboard --logdir=logs --port=6006

^C


## Resize

In [34]:
# Method1 （PIL->resize PIL->resize tensor）
trans_resize = transforms.Resize((512, 512))
img_resize = trans_resize(img)
img_resize = tensor_trans(img_resize)

# Method1 (高版本可以直接输入tensor了)
trans_resize = transforms.Resize((512, 512))
img_resize_1 = trans_resize(tensor_img)

In [33]:
# Method2
trans_resize_2 = transforms.Resize((512, 512))
trans_compose = transforms.Compose([trans_resize_2, tensor_trans])
img_resize_2 = trans_compose(img)

## RandomCrop

In [ ]:
trans_random = transforms.RandomCrop(size=(512, 512))

# torchvision.datasets

In [ ]:
train_set = torchvision.datasets.CIFAR10(root='./data/CIFAR10', train=True, download=True)
test_set = torchvision.datasets.CIFAR10(root='./data/CIFAR10', train=False, download=True)

# DataLoader